language: rust
rust:
  - stable

before_install:
  - sudo apt install clang
  - git clone https://github.com/zeromq/libzmq.git
  - cd libzmq && mkdir -p libzmq_build && cd libzmq_build
  - cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_CURVE=OFF -DZMQ_BUILD_TESTS=OFF ..
  - sudo make -j8 install

cache: cargo
script:
  - cargo build --verbose